#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLiGiaoVien")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuongTrinhDaoTao(ChuongTrinhDaoTao instance);
    partial void UpdateChuongTrinhDaoTao(ChuongTrinhDaoTao instance);
    partial void DeleteChuongTrinhDaoTao(ChuongTrinhDaoTao instance);
    partial void InsertTrinhDoDaoTao(TrinhDoDaoTao instance);
    partial void UpdateTrinhDoDaoTao(TrinhDoDaoTao instance);
    partial void DeleteTrinhDoDaoTao(TrinhDoDaoTao instance);
    partial void InsertDiaChi(DiaChi instance);
    partial void UpdateDiaChi(DiaChi instance);
    partial void DeleteDiaChi(DiaChi instance);
    partial void InsertDonViCongTac(DonViCongTac instance);
    partial void UpdateDonViCongTac(DonViCongTac instance);
    partial void DeleteDonViCongTac(DonViCongTac instance);
    partial void InsertGiaoVien(GiaoVien instance);
    partial void UpdateGiaoVien(GiaoVien instance);
    partial void DeleteGiaoVien(GiaoVien instance);
    partial void InsertHeDaoTao(HeDaoTao instance);
    partial void UpdateHeDaoTao(HeDaoTao instance);
    partial void DeleteHeDaoTao(HeDaoTao instance);
    partial void InsertHocPhan(HocPhan instance);
    partial void UpdateHocPhan(HocPhan instance);
    partial void DeleteHocPhan(HocPhan instance);
    partial void InsertHocVi(HocVi instance);
    partial void UpdateHocVi(HocVi instance);
    partial void DeleteHocVi(HocVi instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertPhanCong(PhanCong instance);
    partial void UpdatePhanCong(PhanCong instance);
    partial void DeletePhanCong(PhanCong instance);
    partial void InsertQuyenHan(QuyenHan instance);
    partial void UpdateQuyenHan(QuyenHan instance);
    partial void DeleteQuyenHan(QuyenHan instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public dbDataContext() : 
				base(global::DAL.Properties.Settings.Default.QuanLiGiaoVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this.GetTable<ChuongTrinhDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<TrinhDoDaoTao> TrinhDoDaoTaos
		{
			get
			{
				return this.GetTable<TrinhDoDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<DiaChi> DiaChis
		{
			get
			{
				return this.GetTable<DiaChi>();
			}
		}
		
		public System.Data.Linq.Table<DonViCongTac> DonViCongTacs
		{
			get
			{
				return this.GetTable<DonViCongTac>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVien> GiaoViens
		{
			get
			{
				return this.GetTable<GiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<HeDaoTao> HeDaoTaos
		{
			get
			{
				return this.GetTable<HeDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<HocPhan> HocPhans
		{
			get
			{
				return this.GetTable<HocPhan>();
			}
		}
		
		public System.Data.Linq.Table<HocVi> HocVis
		{
			get
			{
				return this.GetTable<HocVi>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<PhanCong> PhanCongs
		{
			get
			{
				return this.GetTable<PhanCong>();
			}
		}
		
		public System.Data.Linq.Table<QuyenHan> QuyenHans
		{
			get
			{
				return this.GetTable<QuyenHan>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteGV")]
		public int DeleteGV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaGV", DbType="VarChar(15)")] string maGV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maGV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddGV")]
		public int AddGV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaGV", DbType="VarChar(15)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoDem", DbType="NVarChar(25)")] string hoDem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten", DbType="NVarChar(10)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(5)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="VarChar(20)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="VarChar(15)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocVi", DbType="VarChar(15)")] string hocVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DVCT", DbType="VarChar(15)")] string dVCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(15)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maGV, hoDem, ten, gioiTinh, ngaySinh, soDienThoai, diaChi, hocVi, dVCT, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateGV")]
		public int UpdateGV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaGV", DbType="VarChar(15)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoDem", DbType="NVarChar(25)")] string hoDem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten", DbType="NVarChar(10)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(5)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="VarChar(20)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="VarChar(15)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocVi", DbType="VarChar(15)")] string hocVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DVCT", DbType="VarChar(15)")] string dVCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(15)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maGV, hoDem, ten, gioiTinh, ngaySinh, soDienThoai, diaChi, hocVi, dVCT, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemPC")]
		public int ThemPC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaGV", DbType="VarChar(15)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocPhan", DbType="VarChar(15)")] string hocPhan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocKy", DbType="NVarChar(15)")] string hocKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamHoc", DbType="VarChar(15)")] string namHoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maGV, hocPhan, hocKy, namHoc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllHocPhan")]
		public ISingleResult<GetAllHocPhanResult> GetAllHocPhan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllHocPhanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TimKiemPC")]
		public ISingleResult<TimKiemPCResult> TimKiemPC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamHoc", DbType="VarChar(15)")] string namHoc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocKi", DbType="VarChar(15)")] string hocKi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocPhan", DbType="VarChar(15)")] string hocPhan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaoVien", DbType="VarChar(15)")] string giaoVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CTDT", DbType="VarChar(15)")] string cTDT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), namHoc, hocKi, hocPhan, giaoVien, cTDT);
			return ((ISingleResult<TimKiemPCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaPc")]
		public int XoaPc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaGV", DbType="VarChar(15)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocPhan", DbType="VarChar(15)")] string hocPhan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maGV, hocPhan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DoiMatKhau")]
		public int DoiMatKhau([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="VarChar(30)")] string taiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="VarChar(50)")] string matKhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan, matKhau);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllGiaoVien")]
		public ISingleResult<GetAllGiaoVienResult> GetAllGiaoVien()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllGiaoVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TimKiemGVCPC")]
		public ISingleResult<TimKiemGVCPCResult> TimKiemGVCPC()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TimKiemGVCPCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TimKiemGVDPC")]
		public ISingleResult<TimKiemGVDPCResult> TimKiemGVDPC()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TimKiemGVDPCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TimKiemGV")]
		public ISingleResult<TimKiemGVResult> TimKiemGV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocVi", DbType="VarChar(15)")] string hocVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="VarChar(15)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DVCT", DbType="VarChar(15)")] string dVCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(15)")] string khoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(5)")] string gioiTinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hocVi, diaChi, dVCT, khoa, gioiTinh);
			return ((ISingleResult<TimKiemGVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemTaiKhoan")]
		public int ThemTaiKhoan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTK", DbType="VarChar(30)")] string tenTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="VarChar(50)")] string matKhau, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuyenHan", DbType="VarChar(15)")] string quyenHan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(10)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenTK, matKhau, quyenHan, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaTaiKhoan")]
		public int XoaTaiKhoan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTK", DbType="VarChar(30)")] string tenTK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenTK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaTaiKhoan")]
		public int SuaTaiKhoan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTK", DbType="VarChar(30)")] string tenTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="VarChar(50)")] string matKhau, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuyenHan", DbType="VarChar(15)")] string quyenHan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(10)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenTK, matKhau, quyenHan, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllTaiKhoan")]
		public ISingleResult<GetAllTaiKhoanResult> GetAllTaiKhoan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllTaiKhoanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DisplayHP")]
		public ISingleResult<DisplayHPResult> DisplayHP()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DisplayHPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaHP")]
		public int XoaHP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="VarChar(15)")] string maHP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemHP")]
		public int ThemHP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="VarChar(15)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHP", DbType="NVarChar(50)")] string tenHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoTC", DbType="Int")] System.Nullable<int> soTC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CTDT", DbType="VarChar(15)")] string cTDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(10)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP, tenHP, soTC, cTDT, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TimKiemHP")]
		public ISingleResult<TimKiemHPResult> TimKiemHP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CTDT", DbType="VarChar(15)")] string cTDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="VarChar(10)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cTDT, khoa);
			return ((ISingleResult<TimKiemHPResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuongTrinhDaoTao")]
	public partial class ChuongTrinhDaoTao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenKeHoachDT;
		
		private string _ID_HeDaoTao;
		
		private string _ID_TrinhDoDaoTao;
		
		private EntitySet<HocPhan> _HocPhans;
		
		private EntityRef<TrinhDoDaoTao> _TrinhDoDaoTao;
		
		private EntityRef<HeDaoTao> _HeDaoTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenKeHoachDTChanging(string value);
    partial void OnTenKeHoachDTChanged();
    partial void OnID_HeDaoTaoChanging(string value);
    partial void OnID_HeDaoTaoChanged();
    partial void OnID_TrinhDoDaoTaoChanging(string value);
    partial void OnID_TrinhDoDaoTaoChanged();
    #endregion
		
		public ChuongTrinhDaoTao()
		{
			this._HocPhans = new EntitySet<HocPhan>(new Action<HocPhan>(this.attach_HocPhans), new Action<HocPhan>(this.detach_HocPhans));
			this._TrinhDoDaoTao = default(EntityRef<TrinhDoDaoTao>);
			this._HeDaoTao = default(EntityRef<HeDaoTao>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKeHoachDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKeHoachDT
		{
			get
			{
				return this._TenKeHoachDT;
			}
			set
			{
				if ((this._TenKeHoachDT != value))
				{
					this.OnTenKeHoachDTChanging(value);
					this.SendPropertyChanging();
					this._TenKeHoachDT = value;
					this.SendPropertyChanged("TenKeHoachDT");
					this.OnTenKeHoachDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HeDaoTao", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HeDaoTao
		{
			get
			{
				return this._ID_HeDaoTao;
			}
			set
			{
				if ((this._ID_HeDaoTao != value))
				{
					if (this._HeDaoTao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_HeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._ID_HeDaoTao = value;
					this.SendPropertyChanged("ID_HeDaoTao");
					this.OnID_HeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TrinhDoDaoTao", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_TrinhDoDaoTao
		{
			get
			{
				return this._ID_TrinhDoDaoTao;
			}
			set
			{
				if ((this._ID_TrinhDoDaoTao != value))
				{
					if (this._TrinhDoDaoTao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TrinhDoDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._ID_TrinhDoDaoTao = value;
					this.SendPropertyChanged("ID_TrinhDoDaoTao");
					this.OnID_TrinhDoDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuongTrinhDaoTao_HocPhan", Storage="_HocPhans", ThisKey="ID", OtherKey="ID_ChuongTrinhDaoTao")]
		public EntitySet<HocPhan> HocPhans
		{
			get
			{
				return this._HocPhans;
			}
			set
			{
				this._HocPhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDoDaoTao_ChuongTrinhDaoTao", Storage="_TrinhDoDaoTao", ThisKey="ID_TrinhDoDaoTao", OtherKey="ID", IsForeignKey=true)]
		public TrinhDoDaoTao TrinhDoDaoTao
		{
			get
			{
				return this._TrinhDoDaoTao.Entity;
			}
			set
			{
				TrinhDoDaoTao previousValue = this._TrinhDoDaoTao.Entity;
				if (((previousValue != value) 
							|| (this._TrinhDoDaoTao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrinhDoDaoTao.Entity = null;
						previousValue.ChuongTrinhDaoTaos.Remove(this);
					}
					this._TrinhDoDaoTao.Entity = value;
					if ((value != null))
					{
						value.ChuongTrinhDaoTaos.Add(this);
						this._ID_TrinhDoDaoTao = value.ID;
					}
					else
					{
						this._ID_TrinhDoDaoTao = default(string);
					}
					this.SendPropertyChanged("TrinhDoDaoTao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeDaoTao_ChuongTrinhDaoTao", Storage="_HeDaoTao", ThisKey="ID_HeDaoTao", OtherKey="ID", IsForeignKey=true)]
		public HeDaoTao HeDaoTao
		{
			get
			{
				return this._HeDaoTao.Entity;
			}
			set
			{
				HeDaoTao previousValue = this._HeDaoTao.Entity;
				if (((previousValue != value) 
							|| (this._HeDaoTao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HeDaoTao.Entity = null;
						previousValue.ChuongTrinhDaoTaos.Remove(this);
					}
					this._HeDaoTao.Entity = value;
					if ((value != null))
					{
						value.ChuongTrinhDaoTaos.Add(this);
						this._ID_HeDaoTao = value.ID;
					}
					else
					{
						this._ID_HeDaoTao = default(string);
					}
					this.SendPropertyChanged("HeDaoTao");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HocPhans(HocPhan entity)
		{
			this.SendPropertyChanging();
			entity.ChuongTrinhDaoTao = this;
		}
		
		private void detach_HocPhans(HocPhan entity)
		{
			this.SendPropertyChanging();
			entity.ChuongTrinhDaoTao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrinhDoDaoTao")]
	public partial class TrinhDoDaoTao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenTrinhDoDT;
		
		private EntitySet<ChuongTrinhDaoTao> _ChuongTrinhDaoTaos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenTrinhDoDTChanging(string value);
    partial void OnTenTrinhDoDTChanged();
    #endregion
		
		public TrinhDoDaoTao()
		{
			this._ChuongTrinhDaoTaos = new EntitySet<ChuongTrinhDaoTao>(new Action<ChuongTrinhDaoTao>(this.attach_ChuongTrinhDaoTaos), new Action<ChuongTrinhDaoTao>(this.detach_ChuongTrinhDaoTaos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrinhDoDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTrinhDoDT
		{
			get
			{
				return this._TenTrinhDoDT;
			}
			set
			{
				if ((this._TenTrinhDoDT != value))
				{
					this.OnTenTrinhDoDTChanging(value);
					this.SendPropertyChanging();
					this._TenTrinhDoDT = value;
					this.SendPropertyChanged("TenTrinhDoDT");
					this.OnTenTrinhDoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDoDaoTao_ChuongTrinhDaoTao", Storage="_ChuongTrinhDaoTaos", ThisKey="ID", OtherKey="ID_TrinhDoDaoTao")]
		public EntitySet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this._ChuongTrinhDaoTaos;
			}
			set
			{
				this._ChuongTrinhDaoTaos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDoDaoTao = this;
		}
		
		private void detach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDoDaoTao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaChi")]
	public partial class DiaChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenTP;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenTPChanging(string value);
    partial void OnTenTPChanged();
    #endregion
		
		public DiaChi()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this.OnTenTPChanging(value);
					this.SendPropertyChanging();
					this._TenTP = value;
					this.SendPropertyChanged("TenTP");
					this.OnTenTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_GiaoVien", Storage="_GiaoViens", ThisKey="ID", OtherKey="ID_DiaChi")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonViCongTac")]
	public partial class DonViCongTac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenDV;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    #endregion
		
		public DonViCongTac()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonViCongTac_GiaoVien", Storage="_GiaoViens", ThisKey="ID", OtherKey="ID_DonViCongTac")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.DonViCongTac = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.DonViCongTac = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVien")]
	public partial class GiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _HoDem;
		
		private string _Ten;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _ID_DiaChi;
		
		private string _ID_HocVi;
		
		private string _ID_DonViCongTac;
		
		private string _ID_Khoa;
		
		private EntitySet<PhanCong> _PhanCongs;
		
		private EntityRef<DiaChi> _DiaChi;
		
		private EntityRef<DonViCongTac> _DonViCongTac;
		
		private EntityRef<HocVi> _HocVi;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnHoDemChanging(string value);
    partial void OnHoDemChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnID_DiaChiChanging(string value);
    partial void OnID_DiaChiChanged();
    partial void OnID_HocViChanging(string value);
    partial void OnID_HocViChanged();
    partial void OnID_DonViCongTacChanging(string value);
    partial void OnID_DonViCongTacChanged();
    partial void OnID_KhoaChanging(string value);
    partial void OnID_KhoaChanged();
    #endregion
		
		public GiaoVien()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			this._DiaChi = default(EntityRef<DiaChi>);
			this._DonViCongTac = default(EntityRef<DonViCongTac>);
			this._HocVi = default(EntityRef<HocVi>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoDem", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string HoDem
		{
			get
			{
				return this._HoDem;
			}
			set
			{
				if ((this._HoDem != value))
				{
					this.OnHoDemChanging(value);
					this.SendPropertyChanging();
					this._HoDem = value;
					this.SendPropertyChanged("HoDem");
					this.OnHoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DiaChi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DiaChi
		{
			get
			{
				return this._ID_DiaChi;
			}
			set
			{
				if ((this._ID_DiaChi != value))
				{
					if (this._DiaChi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DiaChiChanging(value);
					this.SendPropertyChanging();
					this._ID_DiaChi = value;
					this.SendPropertyChanged("ID_DiaChi");
					this.OnID_DiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocVi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocVi
		{
			get
			{
				return this._ID_HocVi;
			}
			set
			{
				if ((this._ID_HocVi != value))
				{
					if (this._HocVi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_HocViChanging(value);
					this.SendPropertyChanging();
					this._ID_HocVi = value;
					this.SendPropertyChanged("ID_HocVi");
					this.OnID_HocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DonViCongTac", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DonViCongTac
		{
			get
			{
				return this._ID_DonViCongTac;
			}
			set
			{
				if ((this._ID_DonViCongTac != value))
				{
					if (this._DonViCongTac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DonViCongTacChanging(value);
					this.SendPropertyChanging();
					this._ID_DonViCongTac = value;
					this.SendPropertyChanged("ID_DonViCongTac");
					this.OnID_DonViCongTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhoaChanging(value);
					this.SendPropertyChanging();
					this._ID_Khoa = value;
					this.SendPropertyChanged("ID_Khoa");
					this.OnID_KhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_PhanCong", Storage="_PhanCongs", ThisKey="ID", OtherKey="ID_GiaoVien")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_GiaoVien", Storage="_DiaChi", ThisKey="ID_DiaChi", OtherKey="ID", IsForeignKey=true)]
		public DiaChi DiaChi
		{
			get
			{
				return this._DiaChi.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._DiaChi.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._ID_DiaChi = value.ID;
					}
					else
					{
						this._ID_DiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonViCongTac_GiaoVien", Storage="_DonViCongTac", ThisKey="ID_DonViCongTac", OtherKey="ID", IsForeignKey=true)]
		public DonViCongTac DonViCongTac
		{
			get
			{
				return this._DonViCongTac.Entity;
			}
			set
			{
				DonViCongTac previousValue = this._DonViCongTac.Entity;
				if (((previousValue != value) 
							|| (this._DonViCongTac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonViCongTac.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._DonViCongTac.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._ID_DonViCongTac = value.ID;
					}
					else
					{
						this._ID_DonViCongTac = default(string);
					}
					this.SendPropertyChanged("DonViCongTac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVi_GiaoVien", Storage="_HocVi", ThisKey="ID_HocVi", OtherKey="ID", IsForeignKey=true)]
		public HocVi HocVi
		{
			get
			{
				return this._HocVi.Entity;
			}
			set
			{
				HocVi previousValue = this._HocVi.Entity;
				if (((previousValue != value) 
							|| (this._HocVi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocVi.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._HocVi.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._ID_HocVi = value.ID;
					}
					else
					{
						this._ID_HocVi = default(string);
					}
					this.SendPropertyChanged("HocVi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiaoVien", Storage="_Khoa", ThisKey="ID_Khoa", OtherKey="ID", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._ID_Khoa = value.ID;
					}
					else
					{
						this._ID_Khoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeDaoTao")]
	public partial class HeDaoTao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenHeDT;
		
		private EntitySet<ChuongTrinhDaoTao> _ChuongTrinhDaoTaos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenHeDTChanging(string value);
    partial void OnTenHeDTChanged();
    #endregion
		
		public HeDaoTao()
		{
			this._ChuongTrinhDaoTaos = new EntitySet<ChuongTrinhDaoTao>(new Action<ChuongTrinhDaoTao>(this.attach_ChuongTrinhDaoTaos), new Action<ChuongTrinhDaoTao>(this.detach_ChuongTrinhDaoTaos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHeDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHeDT
		{
			get
			{
				return this._TenHeDT;
			}
			set
			{
				if ((this._TenHeDT != value))
				{
					this.OnTenHeDTChanging(value);
					this.SendPropertyChanging();
					this._TenHeDT = value;
					this.SendPropertyChanged("TenHeDT");
					this.OnTenHeDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeDaoTao_ChuongTrinhDaoTao", Storage="_ChuongTrinhDaoTaos", ThisKey="ID", OtherKey="ID_HeDaoTao")]
		public EntitySet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this._ChuongTrinhDaoTaos;
			}
			set
			{
				this._ChuongTrinhDaoTaos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.HeDaoTao = this;
		}
		
		private void detach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.HeDaoTao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocPhan")]
	public partial class HocPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenHP;
		
		private int _SoTC;
		
		private string _ID_ChuongTrinhDaoTao;
		
		private string _ID_Khoa;
		
		private EntitySet<PhanCong> _PhanCongs;
		
		private EntityRef<ChuongTrinhDaoTao> _ChuongTrinhDaoTao;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenHPChanging(string value);
    partial void OnTenHPChanged();
    partial void OnSoTCChanging(int value);
    partial void OnSoTCChanged();
    partial void OnID_ChuongTrinhDaoTaoChanging(string value);
    partial void OnID_ChuongTrinhDaoTaoChanged();
    partial void OnID_KhoaChanging(string value);
    partial void OnID_KhoaChanged();
    #endregion
		
		public HocPhan()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			this._ChuongTrinhDaoTao = default(EntityRef<ChuongTrinhDaoTao>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this.OnTenHPChanging(value);
					this.SendPropertyChanging();
					this._TenHP = value;
					this.SendPropertyChanged("TenHP");
					this.OnTenHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTC", DbType="Int NOT NULL")]
		public int SoTC
		{
			get
			{
				return this._SoTC;
			}
			set
			{
				if ((this._SoTC != value))
				{
					this.OnSoTCChanging(value);
					this.SendPropertyChanging();
					this._SoTC = value;
					this.SendPropertyChanged("SoTC");
					this.OnSoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ChuongTrinhDaoTao", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_ChuongTrinhDaoTao
		{
			get
			{
				return this._ID_ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ID_ChuongTrinhDaoTao != value))
				{
					if (this._ChuongTrinhDaoTao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ChuongTrinhDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._ID_ChuongTrinhDaoTao = value;
					this.SendPropertyChanged("ID_ChuongTrinhDaoTao");
					this.OnID_ChuongTrinhDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhoaChanging(value);
					this.SendPropertyChanging();
					this._ID_Khoa = value;
					this.SendPropertyChanged("ID_Khoa");
					this.OnID_KhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_PhanCong", Storage="_PhanCongs", ThisKey="ID", OtherKey="ID_HocPhan")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuongTrinhDaoTao_HocPhan", Storage="_ChuongTrinhDaoTao", ThisKey="ID_ChuongTrinhDaoTao", OtherKey="ID", IsForeignKey=true)]
		public ChuongTrinhDaoTao ChuongTrinhDaoTao
		{
			get
			{
				return this._ChuongTrinhDaoTao.Entity;
			}
			set
			{
				ChuongTrinhDaoTao previousValue = this._ChuongTrinhDaoTao.Entity;
				if (((previousValue != value) 
							|| (this._ChuongTrinhDaoTao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuongTrinhDaoTao.Entity = null;
						previousValue.HocPhans.Remove(this);
					}
					this._ChuongTrinhDaoTao.Entity = value;
					if ((value != null))
					{
						value.HocPhans.Add(this);
						this._ID_ChuongTrinhDaoTao = value.ID;
					}
					else
					{
						this._ID_ChuongTrinhDaoTao = default(string);
					}
					this.SendPropertyChanged("ChuongTrinhDaoTao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_HocPhan", Storage="_Khoa", ThisKey="ID_Khoa", OtherKey="ID", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.HocPhans.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.HocPhans.Add(this);
						this._ID_Khoa = value.ID;
					}
					else
					{
						this._ID_Khoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocVi")]
	public partial class HocVi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenHV;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenHVChanging(string value);
    partial void OnTenHVChanged();
    #endregion
		
		public HocVi()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHV
		{
			get
			{
				return this._TenHV;
			}
			set
			{
				if ((this._TenHV != value))
				{
					this.OnTenHVChanging(value);
					this.SendPropertyChanging();
					this._TenHV = value;
					this.SendPropertyChanged("TenHV");
					this.OnTenHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVi_GiaoVien", Storage="_GiaoViens", ThisKey="ID", OtherKey="ID_HocVi")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.HocVi = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.HocVi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _TenKhoa;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
		private EntitySet<HocPhan> _HocPhans;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public Khoa()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			this._HocPhans = new EntitySet<HocPhan>(new Action<HocPhan>(this.attach_HocPhans), new Action<HocPhan>(this.detach_HocPhans));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiaoVien", Storage="_GiaoViens", ThisKey="ID", OtherKey="ID_Khoa")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_HocPhan", Storage="_HocPhans", ThisKey="ID", OtherKey="ID_Khoa")]
		public EntitySet<HocPhan> HocPhans
		{
			get
			{
				return this._HocPhans;
			}
			set
			{
				this._HocPhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_TaiKhoan", Storage="_TaiKhoans", ThisKey="ID", OtherKey="ID_Khoa")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_HocPhans(HocPhan entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_HocPhans(HocPhan entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanCong")]
	public partial class PhanCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_GiaoVien;
		
		private string _ID_HocPhan;
		
		private string _HocKi;
		
		private string _NamHoc;
		
		private EntityRef<GiaoVien> _GiaoVien;
		
		private EntityRef<HocPhan> _HocPhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_GiaoVienChanging(string value);
    partial void OnID_GiaoVienChanged();
    partial void OnID_HocPhanChanging(string value);
    partial void OnID_HocPhanChanged();
    partial void OnHocKiChanging(string value);
    partial void OnHocKiChanged();
    partial void OnNamHocChanging(string value);
    partial void OnNamHocChanged();
    #endregion
		
		public PhanCong()
		{
			this._GiaoVien = default(EntityRef<GiaoVien>);
			this._HocPhan = default(EntityRef<HocPhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GiaoVien", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_GiaoVien
		{
			get
			{
				return this._ID_GiaoVien;
			}
			set
			{
				if ((this._ID_GiaoVien != value))
				{
					if (this._GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_GiaoVienChanging(value);
					this.SendPropertyChanging();
					this._ID_GiaoVien = value;
					this.SendPropertyChanged("ID_GiaoVien");
					this.OnID_GiaoVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocPhan", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_HocPhan
		{
			get
			{
				return this._ID_HocPhan;
			}
			set
			{
				if ((this._ID_HocPhan != value))
				{
					if (this._HocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_HocPhanChanging(value);
					this.SendPropertyChanging();
					this._ID_HocPhan = value;
					this.SendPropertyChanged("ID_HocPhan");
					this.OnID_HocPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKi", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string HocKi
		{
			get
			{
				return this._HocKi;
			}
			set
			{
				if ((this._HocKi != value))
				{
					this.OnHocKiChanging(value);
					this.SendPropertyChanging();
					this._HocKi = value;
					this.SendPropertyChanged("HocKi");
					this.OnHocKiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this.OnNamHocChanging(value);
					this.SendPropertyChanging();
					this._NamHoc = value;
					this.SendPropertyChanged("NamHoc");
					this.OnNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_PhanCong", Storage="_GiaoVien", ThisKey="ID_GiaoVien", OtherKey="ID", IsForeignKey=true)]
		public GiaoVien GiaoVien
		{
			get
			{
				return this._GiaoVien.Entity;
			}
			set
			{
				GiaoVien previousValue = this._GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVien.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._GiaoVien.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._ID_GiaoVien = value.ID;
					}
					else
					{
						this._ID_GiaoVien = default(string);
					}
					this.SendPropertyChanged("GiaoVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_PhanCong", Storage="_HocPhan", ThisKey="ID_HocPhan", OtherKey="ID", IsForeignKey=true)]
		public HocPhan HocPhan
		{
			get
			{
				return this._HocPhan.Entity;
			}
			set
			{
				HocPhan previousValue = this._HocPhan.Entity;
				if (((previousValue != value) 
							|| (this._HocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocPhan.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._HocPhan.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._ID_HocPhan = value.ID;
					}
					else
					{
						this._ID_HocPhan = default(string);
					}
					this.SendPropertyChanged("HocPhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuyenHan")]
	public partial class QuyenHan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _MoTa;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public QuyenHan()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuyenHan_TaiKhoan", Storage="_TaiKhoans", ThisKey="ID", OtherKey="ID_QuyenHan")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.QuyenHan = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.QuyenHan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _MatKhau;
		
		private string _ID_QuyenHan;
		
		private string _ID_Khoa;
		
		private EntityRef<Khoa> _Khoa;
		
		private EntityRef<QuyenHan> _QuyenHan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnID_QuyenHanChanging(string value);
    partial void OnID_QuyenHanChanged();
    partial void OnID_KhoaChanging(string value);
    partial void OnID_KhoaChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._Khoa = default(EntityRef<Khoa>);
			this._QuyenHan = default(EntityRef<QuyenHan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QuyenHan", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_QuyenHan
		{
			get
			{
				return this._ID_QuyenHan;
			}
			set
			{
				if ((this._ID_QuyenHan != value))
				{
					if (this._QuyenHan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_QuyenHanChanging(value);
					this.SendPropertyChanging();
					this._ID_QuyenHan = value;
					this.SendPropertyChanged("ID_QuyenHan");
					this.OnID_QuyenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhoaChanging(value);
					this.SendPropertyChanging();
					this._ID_Khoa = value;
					this.SendPropertyChanged("ID_Khoa");
					this.OnID_KhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_TaiKhoan", Storage="_Khoa", ThisKey="ID_Khoa", OtherKey="ID", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._ID_Khoa = value.ID;
					}
					else
					{
						this._ID_Khoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuyenHan_TaiKhoan", Storage="_QuyenHan", ThisKey="ID_QuyenHan", OtherKey="ID", IsForeignKey=true)]
		public QuyenHan QuyenHan
		{
			get
			{
				return this._QuyenHan.Entity;
			}
			set
			{
				QuyenHan previousValue = this._QuyenHan.Entity;
				if (((previousValue != value) 
							|| (this._QuyenHan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuyenHan.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._QuyenHan.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._ID_QuyenHan = value.ID;
					}
					else
					{
						this._ID_QuyenHan = default(string);
					}
					this.SendPropertyChanged("QuyenHan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetAllHocPhanResult
	{
		
		private string _ID_GiaoVien;
		
		private string _HoTen;
		
		private string _ID_HocPhan;
		
		private string _TenHP;
		
		private System.Nullable<int> _SoTC;
		
		private string _HocKi;
		
		private string _NamHoc;
		
		private string _ID_ChuongTrinhDaoTao;
		
		public GetAllHocPhanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GiaoVien", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_GiaoVien
		{
			get
			{
				return this._ID_GiaoVien;
			}
			set
			{
				if ((this._ID_GiaoVien != value))
				{
					this._ID_GiaoVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(36)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocPhan", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocPhan
		{
			get
			{
				return this._ID_HocPhan;
			}
			set
			{
				if ((this._ID_HocPhan != value))
				{
					this._ID_HocPhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(50)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTC", DbType="Int")]
		public System.Nullable<int> SoTC
		{
			get
			{
				return this._SoTC;
			}
			set
			{
				if ((this._SoTC != value))
				{
					this._SoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKi", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string HocKi
		{
			get
			{
				return this._HocKi;
			}
			set
			{
				if ((this._HocKi != value))
				{
					this._HocKi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this._NamHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ChuongTrinhDaoTao", DbType="VarChar(15)")]
		public string ID_ChuongTrinhDaoTao
		{
			get
			{
				return this._ID_ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ID_ChuongTrinhDaoTao != value))
				{
					this._ID_ChuongTrinhDaoTao = value;
				}
			}
		}
	}
	
	public partial class TimKiemPCResult
	{
		
		private string _ID_GiaoVien;
		
		private string _HoTen;
		
		private string _ID_HocPhan;
		
		private string _TenHP;
		
		private System.Nullable<int> _SoTC;
		
		private string _HocKi;
		
		private string _NamHoc;
		
		private string _ID_ChuongTrinhDaoTao;
		
		public TimKiemPCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GiaoVien", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_GiaoVien
		{
			get
			{
				return this._ID_GiaoVien;
			}
			set
			{
				if ((this._ID_GiaoVien != value))
				{
					this._ID_GiaoVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(36)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocPhan", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocPhan
		{
			get
			{
				return this._ID_HocPhan;
			}
			set
			{
				if ((this._ID_HocPhan != value))
				{
					this._ID_HocPhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(50)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTC", DbType="Int")]
		public System.Nullable<int> SoTC
		{
			get
			{
				return this._SoTC;
			}
			set
			{
				if ((this._SoTC != value))
				{
					this._SoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKi", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string HocKi
		{
			get
			{
				return this._HocKi;
			}
			set
			{
				if ((this._HocKi != value))
				{
					this._HocKi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this._NamHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ChuongTrinhDaoTao", DbType="VarChar(15)")]
		public string ID_ChuongTrinhDaoTao
		{
			get
			{
				return this._ID_ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ID_ChuongTrinhDaoTao != value))
				{
					this._ID_ChuongTrinhDaoTao = value;
				}
			}
		}
	}
	
	public partial class GetAllGiaoVienResult
	{
		
		private string _ID;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _ID_DiaChi;
		
		private string _ID_HocVi;
		
		private string _ID_DonViCongTac;
		
		private string _ID_Khoa;
		
		public GetAllGiaoVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(36) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DiaChi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DiaChi
		{
			get
			{
				return this._ID_DiaChi;
			}
			set
			{
				if ((this._ID_DiaChi != value))
				{
					this._ID_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocVi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocVi
		{
			get
			{
				return this._ID_HocVi;
			}
			set
			{
				if ((this._ID_HocVi != value))
				{
					this._ID_HocVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DonViCongTac", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DonViCongTac
		{
			get
			{
				return this._ID_DonViCongTac;
			}
			set
			{
				if ((this._ID_DonViCongTac != value))
				{
					this._ID_DonViCongTac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
	
	public partial class TimKiemGVCPCResult
	{
		
		private string _ID;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _ID_DiaChi;
		
		private string _ID_HocVi;
		
		private string _ID_DonViCongTac;
		
		private string _ID_Khoa;
		
		public TimKiemGVCPCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(36) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DiaChi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DiaChi
		{
			get
			{
				return this._ID_DiaChi;
			}
			set
			{
				if ((this._ID_DiaChi != value))
				{
					this._ID_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocVi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocVi
		{
			get
			{
				return this._ID_HocVi;
			}
			set
			{
				if ((this._ID_HocVi != value))
				{
					this._ID_HocVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DonViCongTac", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DonViCongTac
		{
			get
			{
				return this._ID_DonViCongTac;
			}
			set
			{
				if ((this._ID_DonViCongTac != value))
				{
					this._ID_DonViCongTac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
	
	public partial class TimKiemGVDPCResult
	{
		
		private string _ID;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _ID_DiaChi;
		
		private string _ID_HocVi;
		
		private string _ID_DonViCongTac;
		
		private string _ID_Khoa;
		
		public TimKiemGVDPCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(36) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DiaChi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DiaChi
		{
			get
			{
				return this._ID_DiaChi;
			}
			set
			{
				if ((this._ID_DiaChi != value))
				{
					this._ID_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocVi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocVi
		{
			get
			{
				return this._ID_HocVi;
			}
			set
			{
				if ((this._ID_HocVi != value))
				{
					this._ID_HocVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DonViCongTac", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DonViCongTac
		{
			get
			{
				return this._ID_DonViCongTac;
			}
			set
			{
				if ((this._ID_DonViCongTac != value))
				{
					this._ID_DonViCongTac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
	
	public partial class TimKiemGVResult
	{
		
		private string _ID;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _ID_DiaChi;
		
		private string _ID_HocVi;
		
		private string _ID_DonViCongTac;
		
		private string _ID_Khoa;
		
		public TimKiemGVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(36) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DiaChi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DiaChi
		{
			get
			{
				return this._ID_DiaChi;
			}
			set
			{
				if ((this._ID_DiaChi != value))
				{
					this._ID_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HocVi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_HocVi
		{
			get
			{
				return this._ID_HocVi;
			}
			set
			{
				if ((this._ID_HocVi != value))
				{
					this._ID_HocVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DonViCongTac", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_DonViCongTac
		{
			get
			{
				return this._ID_DonViCongTac;
			}
			set
			{
				if ((this._ID_DonViCongTac != value))
				{
					this._ID_DonViCongTac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
	
	public partial class GetAllTaiKhoanResult
	{
		
		private string _ID;
		
		private string _MatKhau;
		
		private string _ID_QuyenHan;
		
		private string _ID_Khoa;
		
		public GetAllTaiKhoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QuyenHan", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_QuyenHan
		{
			get
			{
				return this._ID_QuyenHan;
			}
			set
			{
				if ((this._ID_QuyenHan != value))
				{
					this._ID_QuyenHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
	
	public partial class DisplayHPResult
	{
		
		private string _ID;
		
		private string _TenHP;
		
		private int _SoTC;
		
		private string _ID_ChuongTrinhDaoTao;
		
		private string _ID_Khoa;
		
		public DisplayHPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTC", DbType="Int NOT NULL")]
		public int SoTC
		{
			get
			{
				return this._SoTC;
			}
			set
			{
				if ((this._SoTC != value))
				{
					this._SoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ChuongTrinhDaoTao", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_ChuongTrinhDaoTao
		{
			get
			{
				return this._ID_ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ID_ChuongTrinhDaoTao != value))
				{
					this._ID_ChuongTrinhDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
	
	public partial class TimKiemHPResult
	{
		
		private string _ID;
		
		private string _TenHP;
		
		private int _SoTC;
		
		private string _ID_ChuongTrinhDaoTao;
		
		private string _ID_Khoa;
		
		public TimKiemHPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTC", DbType="Int NOT NULL")]
		public int SoTC
		{
			get
			{
				return this._SoTC;
			}
			set
			{
				if ((this._SoTC != value))
				{
					this._SoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ChuongTrinhDaoTao", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ID_ChuongTrinhDaoTao
		{
			get
			{
				return this._ID_ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ID_ChuongTrinhDaoTao != value))
				{
					this._ID_ChuongTrinhDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Khoa
		{
			get
			{
				return this._ID_Khoa;
			}
			set
			{
				if ((this._ID_Khoa != value))
				{
					this._ID_Khoa = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
